# $FreeBSD$

PORTNAME= 	libfap
PORTVERSION=	1.5
CATEGORIES=     comms hamradio
MASTER_SITES= 	http://www.pakettiradio.net/downloads/libfap/${PORTVERSION}/

MAINTAINER= 	akh@nobugware.com
COMMENT=	C port for Ham::APRS::FAP Finnish APRS Parser Perl module

LICENSE=        GPLv2

HAS_CONFIGURE=	yes
USES=		libtool
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
